module.exports = {
  PUSH: 'PUSH',
  POP: 'POP',
  REPLACE: 'REPLACE',
  REPLACE_TO: 'REPLACE_TO',
  REPLACE_AT_INDEX: 'REPLACE_AT_INDEX',
  REPLACE_PREVIOUS: 'REPLACE_PREVIOUS',
  IMMEDIATELY_RESET_ROUTE_STACK: 'IMMEDIATELY_RESET_ROUTE_STACK',
};
